### ISSUE TITLE
KTP api

### ISSUE THREAD

**Issue by a-yahaha** [hantze/npwp-checker#1]
I am looking for ktp or kk api, can you give me some idea, thank your

**Comment by hz081** [comment]
It's forbidden and illegal to crawl KTP & KK API. But if you want to take a risk and against the law, you could crawl from KK from this link : https://bpjs-kesehatan.go.id/bpjs/index.php/pages/detail/2014/15

**Comment by a-yahaha** [comment]
I just want to find an API to check whether name and KTP & KK match, if you have any idea, please let me know

**Comment by t101804** [comment]
> It's forbidden and illegal to crawl KTP & KK API. But if you want to take a risk and against the law, you could crawl from KK from this link : https://bpjs-kesehatan.go.id/bpjs/index.php/pages/detail/2014/15

its not found , do u find any alternatives?
